name: Check no dead code is introduced

on:
  push:
    branches: safe-chain-ci

jobs:
  yarn-ts-prune:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: pass-culture/common-workflows/actions/setup-safe-chain@safe-chain-setup/v1.0.0
      - name: Yarn version
        run: yarn --version
      - name: Install dependencies
        run: yarn setup
      - name: Dead code scan
        run: ./scripts/check_dead_code_introduced.sh
