on:
  push:
    branches:
        - safe-chain-prod


name: Deploy production CMS and static website

permissions:
  id-token: write
  contents: read

jobs:
  deploy-cms-production:
    uses: ./.github/workflows/reusable_cms_deploy.yml
    with:
      project_id: passculture-cls-metier-prod
      environment: production
      workload_identity_provider_secret_name: passculture-cls-metier-ehp/gcp_cls_metier_prod_workload_identity_provider
      cluster_scope: cls-metier
      cluster_environment: prod
      image_tag: main
      secrets_project_id: passculture-cls-metier-ehp
    secrets:
      SECRETS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_CLS_EHP_WORKLOAD_IDENTITY_PROVIDER }}
      SECRETS_SERVICE_ACCOUNT: ${{ secrets.GCP_CLS_EHP_SERVICE_ACCOUNT }}
      PASSCULTURE_GITHUB_ACTION_APP_ID: ${{ secrets.PASSCULTURE_GITHUB_ACTION_APP_ID }}
      PASSCULTURE_GITHUB_ACTION_APP_PRIVATE_KEY: ${{ secrets.PASSCULTURE_GITHUB_ACTION_APP_PRIVATE_KEY }}

  deploy-public-site-production:
    uses: ./.github/workflows/reusable_public_site_deploy.yml
    needs:
      - deploy-cms-production
    with:
      environment: production
      cluster_scope: cls-metier
      cluster_environment: prod
      workload_identity_provider_secret_name: passculture-cls-metier-ehp/gcp_cls_metier_prod_workload_identity_provider
      cms_url: https://siteinstit-cms.passculture.team
      backend_url: https://backend.passculture.app
      secrets_project_id: passculture-cls-metier-ehp
      namespace: site-instit-production
    secrets:
      SECRETS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_CLS_EHP_WORKLOAD_IDENTITY_PROVIDER }}
      SECRETS_SERVICE_ACCOUNT: ${{ secrets.GCP_CLS_EHP_SERVICE_ACCOUNT }}
      PASSCULTURE_GITHUB_ACTION_APP_ID: ${{ secrets.PASSCULTURE_GITHUB_ACTION_APP_ID }}
      PASSCULTURE_GITHUB_ACTION_APP_PRIVATE_KEY: ${{ secrets.PASSCULTURE_GITHUB_ACTION_APP_PRIVATE_KEY }}
